# Exploratory Data Analysis

> Miguel Portela, June 2021

In [1]:
# setwd("C:\\Users\\mangelo.EEG\\Documents\\GitHub\\R_Training\\paneldata")
# setwd("~/Documents/GitHub/R_Training/paneldata/")

rm(list = ls())

# LOG FILE

# sink("Regression.txt")

# LIBRARIES

library(tidyverse) # Modern data science library 
library(ggplot2)
library(haven)
library(funModeling)
library(Hmisc)

library(stargazer)
library(kableExtra)

library(ExPanDaR)
library(SmartEDA)
library(visdat)
library(naniar)

library(plm)       # Panel data analysis library
library(lfe)
library(fixest)
library(clubSandwich)

library(car)       # Companion to applied regression 
library(gplots)    # Various programing tools for plotting data
library(tseries)   # For timeseries analysis
library(lmtest)    # For hetoroskedasticity analysis

library(dplyr)
library(dlookr)
library(MASS)
library(robustbase)
library(sandwich)
library(broom)

── Attaching packages ─────────────────────────────────────── tidyverse 1.3.1 ──

✔ ggplot2 3.3.5     ✔ purrr   0.3.4
✔ tibble  3.1.3     ✔ dplyr   1.0.7
✔ tidyr   1.1.3     ✔ stringr 1.4.0
✔ readr   2.0.1     ✔ forcats 0.5.1

── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()

Loading required package: Hmisc

Loading required package: lattice

Loading required package: survival

Loading required package: Formula


Attaching package: ‘Hmisc’


The following objects are masked from ‘package:dplyr’:

    src, summarize


The following objects are masked from ‘package:base’:

    format.pval, units


funModeling v.1.9.4 :)
Examples and tutorials at livebook.datascienceheroes.com
 / Now in Spanish: librovivodecienciadedatos.ai

Warning message:
“package ‘stargazer’ was built under R version 4.1.2”

Please cite as:


 Hlavac, Marek (2022). stargazer: Well-Formatted Regression and Summary Statistics Tables.

 R package version 5.2.3. https://CRAN.R-project.org/package=stargazer



Attaching package: ‘kableExtra’


The following object is masked from ‘package:dplyr’:

    group_rows


Registered S3 method overwritten by 'GGally':
  method from
  +.gg   ggplot2


Attaching package: ‘plm’


The following objects are masked from ‘package:dplyr’:

    between, lag, lead


Loading required package: Matrix


Attaching package: ‘Matrix’


The following objects are masked from ‘package:tidyr’:

    expand, pack, unpack



Attaching package: ‘lfe’


The following object is masked from ‘package:plm’:

    sargan


(Permanently remove the following message with fixest_startup_msg(FALSE).)
fixest 0.10.0:
- vcov: new argument 'vcov' that replaces 'se' and 'cluster' in all functions
(retro compatibility is ensured).
- function 'dof()' has been renamed into 'ssc()' (i.e. small sample correction).
From fixest 0.9.0 onward: BREAKING changes!
- In i():
    + the first two arguments have been swapped! Now it's i(factor_var,
continuous_var) for interactions.
    + argument 'drop' has been removed (put everything in 'ref' now).
- In feglm():
    + the default family becomes 'gaussian' to be in line with glm(). Hence, for
Poisson estimations, please use fepois() instead.

Registered S3 method overwritten by 'clubSandwich':
  method    from
  bread.mlm sandwich

Loading required package: carData


Attaching package: ‘car’


The following object is masked from ‘package:dplyr’:

    recode


The following object is masked from ‘package:purrr’:

    some



Attaching package: ‘gplots’


The following object is masked from ‘package:stats’:

    lowess


Registered S3 method overwritten by 'quantmod':
  method            from
  as.zoo.data.frame zoo

Loading required package: zoo


Attaching package: ‘zoo’


The following objects are masked from ‘package:base’:

    as.Date, as.Date.numeric



Attaching package: ‘lmtest’


The following object is masked from ‘package:lfe’:

    waldtest



Attaching package: ‘dlookr’


The following object is masked from ‘package:Hmisc’:

    describe


The following object is masked from ‘package:tidyr’:

    extract


The following object is masked from ‘package:base’:

    transform



Attaching package: ‘MASS’


The following object is masked from ‘package:dplyr’:

    select



Attaching package: ‘robustbase’


The following object is masked from ‘package:survival’:

    heart

In [2]:
# DATA

setwd("~/Documents/GitHub/R_Training/EDA/")

nlswork <- read_dta("nlswork.dta")
attach(nlswork)

In [4]:
# View(nlswork)

 names(nlswork)
 head(nlswork)
 str(nlswork)
 dplyr::glimpse(nlswork)

dplyr::glimpse(nlswork$ln_wage)

ExpData(nlswork,type=1)
ExpData(nlswork,type=2)

 [1] "idcode"   "year"     "birth_yr" "age"      "race"     "msp"
 [7] "nev_mar"  "grade"    "collgrad" "not_smsa" "c_city"   "south"
[13] "ind_code" "occ_code" "union"    "wks_ue"   "ttl_exp"  "tenure"
[19] "hours"    "wks_work" "ln_wage"

  idcode year birth_yr age race msp nev_mar grade collgrad not_smsa ⋯ south
1 1      70   51       18  2    0   1       12    0        0        ⋯ 0
2 1      71   51       19  2    1   0       12    0        0        ⋯ 0
3 1      72   51       20  2    1   0       12    0        0        ⋯ 0
4 1      73   51       21  2    1   0       12    0        0        ⋯ 0
5 1      75   51       23  2    1   0       12    0        0        ⋯ 0
6 1      77   51       25  2    0   0       12    0        0        ⋯ 0
  ind_code occ_code union wks_ue ttl_exp  tenure     hours wks_work ln_wage
1  6       3        NA     2     1.083333 0.08333334 20    27       1.451214
2  4       6        NA    22     1.275641 0.08333334 44    10       1.028620
3  4       6         1     0     2.256410 0.91666669 40    51       1.589977
4  4       6        NA     0     2.314102 0.08333334 40     3       1.780273
5  5       6        NA     0     2.775641 0.16666667 10    24       1.777012
6 12       8         0     0     3.775641 1.50000000 32    52       1.778681

tibble [28,534 × 21] (S3: tbl_df/tbl/data.frame)
 $ idcode  : num [1:28534] 1 1 1 1 1 1 1 1 1 1 ...
  ..- attr(*, "label")= chr "NLS id"
  ..- attr(*, "format.stata")= chr "%8.0g"
 $ year    : num [1:28534] 70 71 72 73 75 77 78 80 83 85 ...
  ..- attr(*, "label")= chr "interview year"
  ..- attr(*, "format.stata")= chr "%8.0g"
 $ birth_yr: num [1:28534] 51 51 51 51 51 51 51 51 51 51 ...
  ..- attr(*, "label")= chr "birth year"
  ..- attr(*, "format.stata")= chr "%8.0g"
 $ age     : num [1:28534] 18 19 20 21 23 25 26 28 31 33 ...
  ..- attr(*, "label")= chr "age in current year"
  ..- attr(*, "format.stata")= chr "%8.0g"
 $ race    : num [1:28534] 2 2 2 2 2 2 2 2 2 2 ...
  ..- attr(*, "label")= chr "1=white, 2=black, 3=other"
  ..- attr(*, "format.stata")= chr "%8.0g"
 $ msp     : num [1:28534] 0 1 1 1 1 0 0 0 0 0 ...
  ..- attr(*, "label")= chr "1 if married, spouse present"
  ..- attr(*, "format.stata")= chr "%8.0g"
 $ nev_mar : num [1:28534] 1 0 0 0 0 0 0 0 0 0 ...
  ..- attr(*, "label")= chr "1 if never yet married"
  ..- attr(*, "format.stata")= chr "%8.0g"
 $ grade   : num [1:28534] 12 12 12 12 12 12 12 12 12 12 ...
  ..- attr(*, "label")= chr "current grade completed"
  ..- attr(*, "format.stata")= chr "%8.0g"
 $ collgrad: num [1:28534] 0 0 0 0 0 0 0 0 0 0 ...
  ..- attr(*, "label")= chr "1 if college graduate"
  ..- attr(*, "format.stata")= chr "%8.0g"
 $ not_smsa: num [1:28534] 0 0 0 0 0 0 0 0 0 0 ...
  ..- attr(*, "label")= chr "1 if not SMSA"
  ..- attr(*, "format.stata")= chr "%8.0g"
 $ c_city  : num [1:28534] 1 1 1 1 1 1 1 1 1 1 ...
  ..- attr(*, "label")= chr "1 if central city"
  ..- attr(*, "format.stata")= chr "%8.0g"
 $ south   : num [1:28534] 0 0 0 0 0 0 0 0 0 0 ...
  ..- attr(*, "label")= chr "1 if south"
  ..- attr(*, "format.stata")= chr "%8.0g"
 $ ind_code: num [1:28534] 6 4 4 4 5 12 5 5 5 5 ...
  ..- attr(*, "label")= chr "industry of employment"
  ..- attr(*, "format.stata")= chr "%8.0g"
 $ occ_code: num [1:28534] 3 6 6 6 6 8 6 6 6 6 ...
  ..- attr(*, "label")= chr "occupation"
  ..- attr(*, "format.stata")= chr "%8.0g"
 $ union   : num [1:28534] NA NA 1 NA NA 0 NA 1 1 1 ...
  ..- attr(*, "label")= chr "1 if union"
  ..- attr(*, "format.stata")= chr "%8.0g"
 $ wks_ue  : num [1:28534] 2 22 0 0 0 0 7 0 NA 0 ...
  ..- attr(*, "label")= chr "weeks unemployed last year"
  ..- attr(*, "format.stata")= chr "%8.0g"
 $ ttl_exp : num [1:28534] 1.08 1.28 2.26 2.31 2.78 ...
  ..- attr(*, "label")= chr "total work experience"
  ..- attr(*, "format.stata")= chr "%9.0g"
 $ tenure  : num [1:28534] 0.0833 0.0833 0.9167 0.0833 0.1667 ...
  ..- attr(*, "label")= chr "job tenure, in years"
  ..- attr(*, "format.stata")= chr "%9.0g"
 $ hours   : num [1:28534] 20 44 40 40 10 32 52 45 49 42 ...
  ..- attr(*, "label")= chr "usual hours worked"
  ..- attr(*, "format.stata")= chr "%8.0g"
 $ wks_work: num [1:28534] 27 10 51 3 24 52 4 75 101 97 ...
  ..- attr(*, "label")= chr "weeks worked last year"
  ..- attr(*, "format.stata")= chr "%8.0g"
 $ ln_wage : num [1:28534] 1.45 1.03 1.59 1.78 1.78 ...
  ..- attr(*, "label")= chr "ln(wage/GNP deflator)"
  ..- attr(*, "format.stata")= chr "%9.0g"
 - attr(*, "label")= chr "National Longitudinal Survey.  Young Women 14-26 years of age in 1968"
Rows: 28,534
Columns: 21
$ idcode   <dbl> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2…
$ year     <dbl> 70, 71, 72, 73, 75, 77, 78, 80, 83, 85, 87, 88, 71, 72, 73, 7…
$ birth_yr <dbl> 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 5…
$ age      <dbl> 18, 19, 20, 21, 23, 25, 26, 28, 31, 33, 35, 37, 19, 20, 21, 2…
$ race     <dbl> 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2…
$ msp      <dbl> 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1…
$ nev_mar  <dbl> 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…
$ grade    <dbl> 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 1…
$ collgrad <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…
$ not_smsa <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…
$ c_city   <dbl> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1…
$ south    <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…
$ ind_code <dbl> 6, 4, 4, 4, 5, 12, 5, 5, 5, 5, 5, 5, 4, 4, 4, 4, 4, 4, 4, 4, …
$ occ_code <dbl> 3, 6, 6, 6, 6, 8, 6, 6, 6, 6, 6, 6, 3, 3, 6, 6, 6, 6, 6, 6, 6…
$ union    <dbl> NA, NA, 1, NA, NA, 0, NA, 1, 1, 1, 1, 1, 0, NA, NA, NA, 1, 1,…
$ wks_ue   <dbl> 2, 22, 0, 0, 0, 0, 7, 0, NA, 0, 0, 0, 19, 6, 35, 0, 0, 0, NA,…
$ ttl_exp  <dbl> 1.0833333, 1.2756410, 2.2564101, 2.3141024, 2.7756410, 3.7756…
$ tenure   <dbl> 0.08333334, 0.08333334, 0.91666669, 0.08333334, 0.16666667, 1…
$ hours    <dbl> 20, 44, 40, 40, 10, 32, 52, 45, 49, 42, 45, 48, 40, 40, 40, 4…
$ wks_work <dbl> 27, 10, 51, 3, 24, 52, 4, 75, 101, 97, 95, 70, 13, 22, 17, 39…
$ ln_wage  <dbl> 1.451214, 1.028620, 1.589977, 1.780273, 1.777012, 1.778681, 2…
 num [1:28534] 1.45 1.03 1.59 1.78 1.78 ...
 - attr(*, "label")= chr "ln(wage/GNP deflator)"
 - attr(*, "format.stata")= chr "%9.0g"

   Descriptions                                        Value
1  Sample size (nrow)                                  28534
2  No. of variables (ncol)                             21
3  No. of numeric/interger variables                   21
4  No. of factor variables                             0
5  No. of text variables                               0
6  No. of logical variables                            0
7  No. of identifier variables                         0
8  No. of date variables                               0
9  No. of zero variance variables (uniform)            0
10 %. of variables having complete cases               33.33% (7)
11 %. of variables having >0% and <50% missing cases   66.67% (14)
12 %. of variables having >=50% and <90% missing cases 0% (0)
13 %. of variables having >=90% missing cases          0% (0)

   Index Variable_Name Variable_Type Sample_n Missing_Count Per_of_Missing
1   1    idcode        numeric       28534       0          0.000
2   2    year          numeric       28534       0          0.000
3   3    birth_yr      numeric       28534       0          0.000
4   4    age           numeric       28510      24          0.001
5   5    race          numeric       28534       0          0.000
6   6    msp           numeric       28518      16          0.001
7   7    nev_mar       numeric       28518      16          0.001
8   8    grade         numeric       28532       2          0.000
9   9    collgrad      numeric       28534       0          0.000
10 10    not_smsa      numeric       28526       8          0.000
11 11    c_city        numeric       28526       8          0.000
12 12    south         numeric       28526       8          0.000
13 13    ind_code      numeric       28193     341          0.012
14 14    occ_code      numeric       28413     121          0.004
15 15    union         numeric       19238    9296          0.326
16 16    wks_ue        numeric       22830    5704          0.200
17 17    ttl_exp       numeric       28534       0          0.000
18 18    tenure        numeric       28101     433          0.015
19 19    hours         numeric       28467      67          0.002
20 20    wks_work      numeric       27831     703          0.025
21 21    ln_wage       numeric       28534       0          0.000
   No_of_distinct_values
1  4711
2    15
3    14
4    33
5     3
6     2
7     2
8    19
9     2
10    2
11    2
12    2
13   12
14   13
15    2
16   61
17 4744
18  270
19   85
20  105
21 8173

In [6]:
#freq(nlswork)

Warning message in freq(data.frame(nlswork)):
“None of the input variables are factor nor character”

NULL

In [7]:
eda_report(nlswork,output_dir = "PDF/",output_file = "eda_nlswork.pdf")

processing file: PDF//EDA_Report.Rnw

  |.......................                                               |  33%
  ordinary text without R code

  |...............................................                       |  67%
label: child-section-application (with options)
List of 1
 $ child: chr "02_RunEDA.Rnw"

processing file: PDF/02_RunEDA.Rnw

  |...                                                                   |   4%
  ordinary text without R code

  |.....                                                                 |   7%
label: enrironment (with options)
List of 3
 $ echo   : logi FALSE
 $ warning: logi FALSE
 $ message: logi FALSE

Attaching package: 'gridExtra'


The following object is masked from 'package:dplyr':

    combine

  |........                                                              |  11%
  ordinary text without R code

  |..........                                                            |  15%
label: check_variables (with options)
List of 1
 $ echo: logi FALSE

  |.............                                                         |  19%
   inline R code fragments

  |................                                                      |  22%
label: info_variables (with options)
List of 2
 $ echo   : logi FALSE
 $ results: chr "asis"

  |..................                                                    |  26%
   inline R code fragments

  |.....................                                                 |  30%
label: describe_univariate (with options)
List of 3
 $ echo   : logi FALSE
 $ comment: chr ""
 $ results: chr "asis"

  |.......................                                               |  33%
  ordinary text without R code

  |..........................                                            |  37%
label: normality (with options)
List of 2
 $ echo   : logi FALSE
 $ results: chr "asis"

  |.............................                                         |  41%
  ordinary text without R code

  |...............................                                       |  44%
label: correlations (with options)
List of 2
 $ echo   : logi FALSE
 $ results: chr "asis"

  |..................................                                    |  48%
  ordinary text without R code

  |....................................                                  |  52%
label: plot_correlations (with options)
List of 2
 $ echo   : logi FALSE
 $ results: chr "asis"

  |.......................................                               |  56%
  ordinary text without R code

  |.........................................                             |  59%
label: create_target_by (with options)
List of 2
 $ echo   : logi FALSE
 $ results: chr "asis"

  |............................................                          |  63%
  ordinary text without R code

  |...............................................                       |  67%
label: numeric_variables (with options)
List of 4
 $ echo   : logi FALSE
 $ results: chr "asis"
 $ message: logi FALSE
 $ warning: logi FALSE

  |.................................................                     |  70%
  ordinary text without R code

  |....................................................                  |  74%
label: category_variables (with options)
List of 2
 $ echo   : logi FALSE
 $ results: chr "asis"

  |......................................................                |  78%
  ordinary text without R code

  |.........................................................             |  81%
label: group_correlations (with options)
List of 2
 $ echo   : logi FALSE
 $ results: chr "asis"

  |............................................................          |  85%
  ordinary text without R code

  |..............................................................        |  89%
label: plot_group_correlations (with options)
List of 2
 $ echo   : logi FALSE
 $ results: chr "asis"

  |.................................................................     |  93%
  ordinary text without R code

  |...................................................................   |  96%
label: option_undo (with options)
List of 1
 $ echo: logi FALSE

  |......................................................................| 100%
  ordinary text without R code


  |......................................................................| 100%
  ordinary text without R code

output file: PDF//eda_nlswork.tex

In [ ]:
# STATISTICS

## EDA

# eda_report(nlswork,output_dir = "EDA/",output_file = "eda_nlswork.pdf")

summary(nlswork[,"grade"])

ExpNumStat(nlswork,by="A",Outlier = TRUE,round=2,Qnt=c(0.1,0.20,0.50))

ExpCTable(nlswork)

ExpCatViz(nlswork)

# ExpNumViz(nlswork,Page=c(6,2))

## TRY IN A 'JUPYTER NOTEBOOK': ExpNumViz(nlswork)

ExpNumViz(nlswork)

In [ ]:
eda_report(nlswork,output_dir = "EDA/",output_file = "eda_nlswork.pdf")

In [ ]:
ExpOutliers(nlswork,varlist=c("ln_wage"))

In [ ]:
vis_dat(nlswork)

# vis_miss(nlswork) # ALTERNATIVE

gg_miss_upset(nlswork)

In [ ]:
## ExPanD(): import the data 'nlswork.dta' and 'ExPanD()' in the Console

In [ ]:
summary(nlswork)

stargazer(nlswork,
          title = "Summary statistics",
          label = "tb:statistcis",
          table.placement = "ht",
          header=FALSE)

## or

stargazer(nlswork,
          title = "Summary statistics",
          label = "tb:statistcis",
          table.placement = "ht",
          header=FALSE,type="text")

## or a subset of variables

nlswork %>%
  dplyr::select(ln_wage,grade) %>% 
  stargazer(title="Shorter statistics",
            label="tb:statistics:short",
            table.placement = "ht",
            header=FALSE,
            type="text")

In [ ]:
# *drop missing values*

nlswork_clean <-  drop_na(subset(nlswork,select = c(idcode, year, ln_wage, union, collgrad, age, tenure, not_smsa, south, c_city)))

# *Create new variables*

nlswork_clean$agesq <- nlswork_clean$age^2
nlswork_clean$tensq <- nlswork_clean$tenure^2

ExpData(nlswork_clean,type=1)
ExpData(nlswork_clean,type=2)

nlswork_clean <- nlswork_clean[order(idcode,year),]

attach(nlswork_clean)

plot(nlswork$grade,nlswork$ln_wage)

In [ ]:
nlswork %>%
  ggplot(aes(grade,ln_wage)) +
  labs(title = "Ln Wage vs. Grade") +
  ylab("Ln Wage") +
  xlab("Grade") +
  geom_point()
  
  ## SAVE YOUR GRAPH

    ggsave("figures/graph1.png")

In [ ]:
# REGRESSION ANALYSIS

In [ ]:
# Exploratory Data Analysis

# coplot(ln_wage ~ year|idcode,type="b",data = nlswork_clean)
# scatterplot(ln_wage ~ year|idcode,data = nlswork_clean)

plotmeans(ln_wage ~ year ,data = nlswork_clean)

# *Estimating a Mincerian Wage Equation*

# *POLS estimator with cluster-robust standard errors*

# *Q1*
# Pooled OLS model

ols <- lm(data = nlswork_clean, ln_wage ~ union +
            collgrad +age +agesq +tenure +tensq +
            not_smsa +south +c_city)
summary(ols)

pols <- plm(data = nlswork_clean, ln_wage ~ union +
              collgrad +age +agesq +tenure +tensq +
              not_smsa +south +c_city, model="pooling", index=c("idcode", "year"))
summary(pols)

stargazer(ols,pols,title = "Regression analysis", 
          model.numbers = FALSE,
          column.labels = c("OLS","Pooled"),
          label = "regressions",
          table.placement = "!ht",
          notes.append = FALSE,
          notes.align="l",
          notes="Standard errors in parentheses.",
          header = FALSE,
          no.space = TRUE,
          covariate.labels = c("Union","Collage Graduate","Age","Age sqrd.","Tenure","Tenure sqrd.","Not SMSA","South","City"),
          omit = c("Constant"),
          omit.stat = c("adj.rsq","f","ser"),
          digits = 6,
          digits.extra = 7,
          omit.yes.no = c("Constant",""),
          dep.var.caption="",
          dep.var.labels.include = FALSE,
          style = "qje",
          type="text")

In [ ]:
# CLUSTERED Standard-errors

pols_robust <- coeftest(pols, function(x) vcovHC(x, type = 'sss')) 

stargazer(pols,pols_robust,title = "Regression analysis", 
          model.numbers = FALSE,
          column.labels = c("Pooled","Pooled (cluster)"),
          label = "regressions",
          table.placement = "!ht",
          notes.append = FALSE,
          notes.align="l",
          notes="Standard errors in parentheses.",
          header = FALSE,
          no.space = TRUE,
          covariate.labels = c("Union","Collage graduate","Age","Age sqrd.","Tenure","Tenure sqrd.","Not SMSA","South","City"),
          omit = c("Constant"),
          omit.stat = c("adj.rsq","f","ser"),
          digits = 6,
          digits.extra = 7,
          omit.yes.no = c("Constant",""),
          dep.var.caption="",
          dep.var.labels.include = FALSE,
          style = "qje",
          type="text")

# // Final slide 20
# *Q2*
#   
#   *Random effects estimator (RE)*

# SEE THE DISCUSSION HERE for the comparison between R and Stata
# https://stats.stackexchange.com/questions/421374/different-results-from-random-effects-plm-r-and-xtreg-stata
# R and Stata treat differently unbalanced panels

# for a balanced panel we have

nlswork_balanced <- read_dta("nlswork_balanced.dta")

re_balanced <- plm(data = nlswork_balanced, ln_wage ~ union +
                     collgrad +age +agesq +tenure +tensq +
                     not_smsa +south +c_city, model="random",
                   index=c("idcode", "year"))
summary(re_balanced)

re <- plm(data = nlswork_clean, ln_wage ~ union +
            collgrad +age +agesq +tenure +tensq +
            not_smsa +south +c_city, model="random",
          index=c("idcode", "year"))
summary(re)

re_robust <- coeftest(re, function(x) vcovHC(x, type = 'sss')) 

stargazer(pols,pols_robust,re,re_robust,title = "Regression analysis", 
          model.numbers = FALSE,
          column.labels = c("Pooled","Pooled (cluster)","RE","RE (cluster"),
          label = "regressions",
          table.placement = "!ht",
          notes.append = FALSE,
          notes.align="l",
          notes="Standard errors in parentheses.",
          header = FALSE,
          no.space = TRUE,
          covariate.labels = c("Union","Collage Graduate","Age","Age sqrd.","Tenure","Tenure sqrd.","Not SMSA","South","City"),
          omit = c("Constant"),
          omit.stat = c("adj.rsq","f","ser"),
          digits = 6,
          digits.extra = 7,
          omit.yes.no = c("Constant",""),
          dep.var.caption="",
          dep.var.labels.include = FALSE,
          style = "qje",
          type="text")

# *LM test for the presence of unobserved effects*

plmtest(pols, type=c("bp"))

kable(tidy(plmtest(pols, type=c("bp"))), format = "simple",caption=
        "LM test for the presence of unobserved effects")

# //Final slide 32
# 
# *Q3*
#   
#   *Fixed effects estimator (FE)*

fe <- plm(data = nlswork_clean, ln_wage ~ union +
            collgrad +age +agesq +tenure +tensq +
            not_smsa +south +c_city, model="within", index=c("idcode", "year"))
summary(fe)

stargazer(fe,title = "Regression analysis", 
          model.numbers = FALSE,
          column.labels = c("FE"),
          label = "regressions",
          table.placement = "!ht",
          notes.append = FALSE,
          notes.align="l",
          notes="Standard errors in parentheses.",
          header = FALSE,
          no.space = TRUE,
          covariate.labels = c("Union","Age","Age sqrd.","Tenure","Tenure sqrd.","Not SMSA","South","City"),
          omit = c("Constant"),
          omit.stat = c("adj.rsq","f","ser"),
          digits = 6,
          digits.extra = 7,
          omit.yes.no = c("Constant",""),
          dep.var.caption="",
          dep.var.labels.include = FALSE,
          style = "qje",
          type="text")

# Testing for fixed effects, null: OLS better than fixed
# 'F test for individual effects' <<==>> 'F test that all u_i=0'

ols_0 <- lm(data = nlswork_clean, ln_wage ~ union +
              age +agesq +tenure +tensq +
              not_smsa +south +c_city)
summary(ols_0)

pFtest(fe, ols_0)

# generate fixed-effects

# nlswork_clean$specific_effects <- fixef(fe)

# *Q3.1*

fe_robust <- coeftest(fe, function(x) vcovHC(x, type = 'sss')) 

stargazer(ols_0,fe,fe_robust,title = "Regression analysis", 
          model.numbers = FALSE,
          column.labels = c("OLS","FE","FE (cluster)"),
          label = "regressions",
          table.placement = "!ht",
          notes.append = FALSE,
          notes.align="l",
          notes="Standard errors in parentheses.",
          header = FALSE,
          no.space = TRUE,
          covariate.labels = c("Union","Age","Age sqrd.","Tenure","Tenure sqrd.","Not SMSA","South","City"),
          omit = c("Constant"),
          omit.stat = c("adj.rsq","f","ser"),
          digits = 6,
          digits.extra = 7,
          omit.yes.no = c("Constant",""),
          dep.var.caption="",
          dep.var.labels.include = FALSE,
          style = "qje",
          type="text")

# *Q3.2*

linearHypothesis(ols,c("age=0","agesq=0"))
linearHypothesis(ols,c("age=0","agesq=0"), white.adjust = "hc1")

Wald_test(fe, vcov = "CR1", cluster = idcode, constraints = constrain_zero(c("age","agesq")), test = "Naive-F")


# *LSDV Estimator=FE estimator* <<==>> takes too long
# *using a smaller sample*

nlswork_balanced <- read_dta("nlswork_balanced_small.dta")

LSDV <- lm(data = nlswork_balanced, ln_wage ~ union +
             age +agesq +tenure +tensq +
             not_smsa +south +c_city + factor(idcode))
summary(LSDV)

# //Final slide 35
# 
# *Q4*
#   *Hausman test*

fe_0 <- plm(data = nlswork_clean, ln_wage ~ union +
              collgrad +age +agesq +tenure +tensq +
              not_smsa +south +c_city, model="within", index=c("idcode", "year"))
re_0 <- plm(data = nlswork_clean, ln_wage ~ union +
              collgrad +age +agesq +tenure +tensq +
              not_smsa +south +c_city, model="random", index=c("idcode", "year"))

phtest(fe_0, re_0)    

#   //Final slide 46
# 
# *Q5*
#   *BE estimator

be <- plm(data = nlswork_clean, ln_wage ~ union +
            collgrad +age +agesq +tenure +tensq +
            not_smsa +south +c_city, model="between",
          index=c("idcode", "year"))
summary(be)

# //Final slide 53
# 
# *Q6*
#   *FD estimator*

fd <- plm(data = nlswork_clean, ln_wage ~ 0 + union +
            collgrad +age +agesq +tenure +tensq +
            not_smsa +south +c_city, model="fd",
          index=c("idcode", "year"))
summary(fd)

# *Output Table*

stargazer(pols,re,fe,be,title = "Regression analysis", 
          model.numbers = FALSE,
          column.labels = c("OLS","RE","FE","BE"),
          label = "regressions",
          table.placement = "!ht",
          notes.append = FALSE,
          notes.align="l",
          notes="Standard errors in parentheses.",
          header = FALSE,
          no.space = TRUE,
          omit = c("Constant"),
          omit.stat = c("adj.rsq","f","ser"),
          digits = 6,
          digits.extra = 7,
          omit.yes.no = c("Constant",""),
          dep.var.caption="",
          dep.var.labels.include = FALSE,
          style = "qje",
          type="text")

# *FURTHER SPECIFICATION TESTS FOR PANEL DATA*
#   
#   
#   // # Test for heteroskedasticity within panel data
#   

# takes too long to compute

# bptest(data = nlswork_clean, ln_wage ~ 0 + union +
#          collgrad +age +agesq +tenure +tensq +
#          not_smsa +south +c_city + factor(idcode), studentize=F)

# // # Test of serial correlation within panel data

# Unobserved effects test <<>> Wooldridge's test for unobserved individual effects <<>>

pwtest(data = nlswork_clean, ln_wage ~ union +
         collgrad +age +agesq +tenure +tensq +
         not_smsa +south +c_city)

# Locally robust tests for serial correlation or random effects <<>> Baltagi and Li AR-RE joint test - balanced panel <<>>

pbsytest(data = nlswork_balanced, ln_wage ~ union +
           collgrad +age +agesq +tenure +tensq +
           not_smsa +south +c_city, test="j")
# General serial correlation tests <<>> Breusch-Godfrey/Wooldridge test for serial correlation in panel models <<>>

pbgtest(fe, order = 2)

# Wooldridge's test for serial correlation in FE panels

pwartest(data = nlswork_balanced, ln_wage ~ union +
           collgrad +age +agesq +tenure +tensq +
           not_smsa +south +c_city)

# Wooldridgeâs first-difference-based test

pwfdtest(data = nlswork_balanced, ln_wage ~ union +
           collgrad +age +agesq +tenure +tensq +
           not_smsa +south +c_city)

pwfdtest(data = nlswork_balanced, ln_wage ~ union +
           collgrad +age +agesq +tenure +tensq +
           not_smsa +south +c_city, h0="fe")

# Tests for cross-sectional dependence

pcdtest(data = nlswork_balanced, ln_wage ~ union +
          collgrad +age +agesq +tenure +tensq +
          not_smsa +south +c_city)

# HIGH FIMENSIONAL FIXED-EFFECTS

## CHECK: 'lfe' and 'fixest'
### https://github.com/sgaure/lfe
### https://github.com/lrberge/fixest

# *including 1 fixed effect*

HDFE1a <- feols(data = nlswork_clean, ln_wage ~ union +
                  age +agesq +tenure +tensq +
                  not_smsa +south +c_city | idcode)
summary(HDFE1a)

HDFE1b <- felm(data = nlswork_clean, ln_wage ~ union +
                 age +agesq +tenure +tensq +
                 not_smsa +south +c_city | idcode, clustervar=c("idcode"))
summary(HDFE1b)

# *including a 2nd fixed effect*

HDFE2a <- feols(data = nlswork_clean, ln_wage ~ union +
                  age +agesq +tenure +tensq +
                  not_smsa +south +c_city | idcode + year)
summary(HDFE2a)

HDFE2b <- felm(data = nlswork_clean, ln_wage ~ union +
                 age +agesq +tenure +tensq +
                 not_smsa +south +c_city  | idcode + year, clustervar=c("idcode"))
summary(HDFE2b)

##################################      

# sink()

# Miscelaneous

In [ ]:
glimpse(nlswork)
status(nlswork)
freq(nlswork$union)
describe(nlswork)
plot_num(nlswork)
profiling_num(nlswork)